name: pknives
description: "Application for sharpening knives and tools."

version: 17.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  sqflite: ^2.4.1
  sensors_plus: ^6.0.1
  audioplayers: ^6.0.0
  shared_preferences: ^2.3.2
  adapty_flutter: ^2.10.2
  adapty_ui_flutter: ^2.1.3
  image_picker: ^1.1.2
  image: ^4.1.6
  path_provider: ^2.0.4
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.1
  firebase_storage: ^12.3.7
  http: ^1.2.2
  flutter_exit_app: ^1.1.4
  share_plus: ^10.0.2
  intl: ^0.17.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript.ttf
    - family: Gamestation
      fonts:
        - asset: assets/fonts/GamestationCondensed.otf

